# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementresult',
            name='amperageFilter',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='isMainResult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='voltageFilter',
            field=models.FloatField(null=True),
        ),
    ]
