# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0002_auto_20160519_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementresult',
            old_name='amperageFilter',
            new_name='amperageFilterMax',
        ),
        migrations.RenameField(
            model_name='measurementresult',
            old_name='voltageFilter',
            new_name='amperageFilterMin',
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='voltageFilterMax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='voltageFilterMin',
            field=models.FloatField(null=True),
        ),
    ]
