# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0003_auto_20160519_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementresult',
            name='movingAverage',
            field=models.FloatField(null=True),
        ),
    ]
