# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0004_measurementresult_movingaverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementresult',
            old_name='movingAverage',
            new_name='amperageMovingAverage',
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='voltageMovingAverage',
            field=models.FloatField(null=True),
        ),
    ]
