# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0005_auto_20160527_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appnoise.Point'),
            preserve_default=False,
        ),
    ]
