# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0006_auto_20160602_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
