# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoise', '0008_auto_20160605_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
